services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    image: com_agent:latest 
    volumes:
      - ./src/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env.local