services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.local
    image: com_agent:latest 
    volumes:
      - ./src/:/app/
    ports:
      - 8000:8000
    env_file:
      - .env.local
    depends_on:
      - db
  db:
    image: pgvector/pgvector:pg16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U com_agent"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 45s
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=com_agent
      - POSTGRES_PASSWORD=com_agent
      - POSTGRES_DB=com_agent

volumes:
  postgres_data:
