[tool.ruff]
line-length = 88
indent-width = 4

target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"


[tool.pyright]
venvPath = "."
venv = ".venv"

typeCheckingMode = "basic"

include = ["apps"]
exclude = [
    "**/__pycache__",
    ".venv",
]
reportMissingImports = true
reportMissingTypeStubs = false
reportGeneralTypeIssues = true

pythonVersion = "3.12"
pythonPlatform = "Linux"
